import os

repos = [
    "https://gitcode.com/Cangjie-TPC/chinamobiledb-driver",
    "https://gitcode.com/Cangjie-TPC/protobuf4cj",
    "https://gitcode.com/Cangjie-TPC/charset4cj",
    "https://gitcode.com/Cangjie-TPC/diffutils4cj",
    "https://gitcode.com/Cangjie-TPC/html4cj",
    "https://gitcode.com/Cangjie-TPC/zlib4cj",
    "https://gitcode.com/Cangjie-TPC/apm_sdk",
    "https://gitcode.com/Cangjie-TPC/gataway-cj",
    "https://gitcode.com/Cangjie-TPC/hystrix-cj",
    "https://gitcode.com/Cangjie-TPC/vcard4cj",
    "https://gitcode.com/Cangjie-TPC/toml4cj",
    "https://gitcode.com/Cangjie-TPC/kv4cj",
    "https://gitcode.com/Cangjie-TPC/compress4cj",
    "https://gitcode.com/Cangjie-TPC/io4cj",
    "https://gitcode.com/Cangjie-TPC/bzip2-ffi",
    "https://gitcode.com/Cangjie-TPC/oauth4cj",
    "https://gitcode.com/Cangjie-TPC/commonmark4cj",
    "https://gitcode.com/Cangjie-TPC/zip4cj",
    "https://gitcode.com/Cangjie-TPC/lite-eventbus-cj",
    "https://gitcode.com/Cangjie-TPC/quartz4cj",
    "https://gitcode.com/Cangjie-TPC/xml_stream",
    "https://gitcode.com/Cangjie-TPC/pkcs4cj",
    "https://gitcode.com/Cangjie-TPC/opengauss-driver",
    "https://gitcode.com/Cangjie-TPC/gifdrawable4cj",
    "https://gitcode.com/Cangjie-TPC/disklrucache4cj",
    "https://gitcode.com/Cangjie-TPC/chardet4cj",
    "https://gitcode.com/Cangjie-TPC/jwt4cj",
    "https://gitcode.com/Cangjie-TPC/mp3tag4cj",
    "https://gitcode.com/Cangjie-TPC/qrcode4cj",
    "https://gitcode.com/Cangjie-TPC/mp4parser4cj",
    "https://gitcode.com/Cangjie-TPC/chart4cj",
    "https://gitcode.com/Cangjie-TPC/log-cj",
    "https://gitcode.com/Cangjie-TPC/editor4cj",
    "https://gitcode.com/Cangjie-TPC/prism4cj",
    "https://gitcode.com/Cangjie-TPC/odbc4cj",
    "https://gitcode.com/Cangjie-TPC/rpc4cj",
    "https://gitcode.com/Cangjie-TPC/formula-ffi",
    "https://gitcode.com/Cangjie-TPC/pinyin4cj",
    "https://gitcode.com/Cangjie-TPC/asnone4cj",
    "https://gitcode.com/Cangjie-TPC/eventbus4cj",
    "https://gitcode.com/Cangjie-TPC/ahocorasick4cj",
    "https://gitcode.com/Cangjie-TPC/dataORM4cj",
    "https://gitcode.com/Cangjie-TPC/mysqlclient-ffi",
    "https://gitcode.com/Cangjie-TPC/droplet",
    "https://gitcode.com/Cangjie-TPC/rebound4cj",
    "https://gitcode.com/Cangjie-TPC/xml-ffi",
    "https://gitcode.com/Cangjie-TPC/markdown4cj",
    "https://gitcode.com/Cangjie-TPC/mqtt4cj",
    "https://gitcode.com/Cangjie-TPC/ijkplayer-ffi",
    "https://gitcode.com/Cangjie-TPC/httpclient4cj",
    "https://gitcode.com/Cangjie-TPC/phonenumber4cj",
    "https://gitcode.com/Cangjie-TPC/flexSearch4cj",
    "https://gitcode.com/Cangjie-TPC/oss-sdk",
    "https://gitcode.com/Cangjie-TPC/s3-sdk",
    "https://gitcode.com/Cangjie-TPC/config-client",
    "https://gitcode.com/Cangjie-TPC/config-server",
    "https://gitcode.com/Cangjie-TPC/uuid4cj",
    "https://gitcode.com/Cangjie-TPC/ini4cj",
    "https://gitcode.com/Cangjie-TPC/download4cj",
    "https://gitcode.com/Cangjie-TPC/upload4cj",
    "https://gitcode.com/Cangjie-TPC/yaml4cj",
    "https://gitcode.com/Cangjie-TPC/crypto4cj",
    "https://gitcode.com/Cangjie-TPC/CangChain",
    "https://gitcode.com/Cangjie-TPC/redis-sdk",
    "https://gitcode.com/Cangjie-TPC/hyperion",

]

if __name__ == '__main__':
    # clone to code/*
    for repo in repos:
        os.system(f"git clone {repo} code/{repo.split('/')[-1]}")
